# Generated by Django 3.2.17 on 2023-12-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20231222_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
